exports.run = (client, message, args, Discord) => {
  if (message.mentions.users.first()) {
    var ji = "The thing about me, Chris, is I just shrugged off a ban in 2 seconds, where as you're probably treating it like a huge life achievment and talking all kinds of shit to your cancerous audience. If you honestly think me not being apart of that server is going to effect my life, you must be a real sad human being. I have two jobs and a group of people that hang out in person every single day for the last 13 years of my life, where as you probably only hang out with your mother and you are just sitting on a computer monitoring some pathetic server about a fairly poor youtube channel. Who looks more pathetic here? Thought so. It's all fun and games until somebody disables your PID too. Talk all that shit but you won't do nothing, especially when you fuck with the wrong person. And please, PLEASE try to act like tough shit. TRY to pretend like you don't care or that \"I cant do anything\". Because guess what, have you heard of the youtuber \"AngleWing20\"? He had over 7 million subscribers and a discord server with around 6 thousand members? Where are they? Oh that's right. I took his youtube account, deleted all his shit, deactivated it, and did the same to his discord. All you have to do is look at the proof. So goodluck Young Child (; (P.S Blocking immediately after sending message. Ill never see a single pathetic word you say so go ahead and waste your time writing a \"tough\" reply)";
    var msg = ji.replace('Chris', message.mentions.users.first().username);
    message.channel.send(msg);
  } else { message.channel.send("The thing about me, Chris, is I just shrugged off a ban in 2 seconds, where as you're probably treating it like a huge life achievment and talking all kinds of shit to your cancerous audience. If you honestly think me not being apart of that server is going to effect my life, you must be a real sad human being. I have two jobs and a group of people that hang out in person every single day for the last 13 years of my life, where as you probably only hang out with your mother and you are just sitting on a computer monitoring some pathetic server about a fairly poor youtube channel. Who looks more pathetic here? Thought so. It's all fun and games until somebody disables your PID too. Talk all that shit but you won't do nothing, especially when you fuck with the wrong person. And please, PLEASE try to act like tough shit. TRY to pretend like you don't care or that \"I cant do anything\". Because guess what, have you heard of the youtuber \"AngleWing20\"? He had over 7 million subscribers and a discord server with around 6 thousand members? Where are they? Oh that's right. I took his youtube account, deleted all his shit, deactivated it, and did the same to his discord. All you have to do is look at the proof. So goodluck Young Child (; (P.S Blocking immediately after sending message. Ill never see a single pathetic word you say so go ahead and waste your time writing a \"tough\" reply)"); }
};


exports.conf = {
  name: 'goodluck',
  description: 'GL',
  usage: 'goodluck',
  aliases: ['gl'],
};
